-- GROUP BY, TO_NUMVER(09시에서 0을 제거하기 위함)
SELECT TO_NUMBER(TO_CHAR(DATETIME,'HH24')) AS HOUR, 
       COUNT(*) AS COUNT
FROM ANIMAL_OUTS
GROUP BY TO_CHAR(DATETIME, 'HH24')
HAVING TO_CHAR(DATETIME,'HH24') BETWEEN 09 AND 19
ORDER BY HOUR;

-- INLINE VIEW 사용
SELECT HOUR, COUNT(HOUR) AS COUNT
FROM
    (SELECT TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HOUR
      FROM ANIMAL_OUTS)
GROUP BY HOUR
HAVING HOUR BETWEEN 9 AND 19
ORDER BY HOUR

-- EXTRACT, REGEXP_LIKE etc.. 사용하는 방법이 있으니 한 번 쯤은 고안해볼 것
