SELECT  A.TITLE,
        A.BOARD_ID,
        B.REPLY_ID,
        B.WRITER_ID,
        B.CONTENTS,
        TO_CHAR(B.CREATED_DATE,'YYYY-MM-DD') AS CREATED_DATE
FROM    USED_GOODS_BOARD A
        ,USED_GOODS_REPLY B
WHERE   A.CREATED_DATE BETWEEN TO_DATE('20221001','YYYY-MM-DD') AND TO_DATE('20221031','YYYY-MM-DD')
AND     A.BOARD_ID = B.BOARD_ID
ORDER BY B.CREATED_DATE, A.TITLE ASC