SELECT  UGB.TITLE,
        UGB.BOARD_ID,
        UGR.REPLY_ID,
        UGR.WRITER_ID,
        UGR.CONTENTS,
        TO_CHAR(UGR.CREATED_DATE,'YYYY-MM-DD') AS CREATED_DATE
FROM    USED_GOODS_BOARD UGB
        ,USED_GOODS_REPLY UGR
WHERE   UGB.CREATED_DATE BETWEEN TO_DATE('20221001','YYYY-MM-DD') AND TO_DATE('20221031','YYYY-MM-DD')
AND     UGR.BOARD_ID = UGB.BOARD_ID
ORDER BY UGR.CREATED_DATE, UGB.TITLE ASC