-- EQUI JOIN
SELECT B.CATEGORY, SUM(BS.SALES) AS TOTAL_SALES
FROM BOOK B, BOOK_SALES BS
WHERE BS.SALES_DATE BETWEEN TO_DATE(20220101,'YYYY-MM-DD') AND TO_DATE(20220131, 'YYYY-MM-DD')
AND B.BOOK_ID = BS.BOOK_ID
GROUP BY B.CATEGORY

/* WHERE EXTRACT(YEAR FROM BS.SALES) = 2022 AND EXTRACT(MONTH FROM BS.SALES) = 1
   WHERE 1=1
   AND A.BOOK_ID = B.BOOK_ID
   AND TO_CHAR(A.SALES_DATE,'YYYYMM')  = '202201' */

ORDER BY B.CATEGORY ASC;

-- INNER JOIN, LIKE
SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES 
FROM BOOK AS B
INNER JOIN BOOK_SALES AS S ON B.BOOK_ID = S.BOOK_ID
WHERE S.SALES_DATE LIKE '2022-01%'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC;
