-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(BS.SALES) AS TOTAL_SALES
FROM BOOK B, BOOK_SALES BS
WHERE BS.SALES_DATE BETWEEN TO_DATE(20220101,'YYYY-MM-DD') AND TO_DATE(20220131, 'YYYY-MM-DD')
AND B.BOOK_ID = BS.BOOK_ID
GROUP BY B.CATEGORY

/*WHERE EXTRACT(YEAR FROM BS.SALES) = 2022 AND EXTRACT(MONTH FROM BS.SALES) = 1*/

ORDER BY B.CATEGORY ASC;